export const get_question_thr_id_type = 'get_question_thr_id'
export const get_question_type = 'get_question'
export const get_question_of_survey_type = 'get_question_of_survey'
export const post_question_type = 'post_question'
export const put_question_type = 'put_question'
