import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux_provider";
import { Toaster } from "react-hot-toast";
import SessionProvider from "@/config/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}><SessionProvider session={session}> <ReduxProvider> {children}  <Toaster position="top-center" /></ReduxProvider></SessionProvider></body>
    </html>
  );
}
