import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/store/redux_provider";
import { Toaster } from "react-hot-toast";
// import Sidebar from "@/app/(layouts)/side_bar/Sidebar";
import style from "@/app/ui/layout.module.css"
import SideBar from "@/app/(layouts)/header/Header";
// import  Header  from "@/app/(layouts)/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>   <ReduxProvider> <SideBar> {children} </SideBar> <Toaster position="top-center" /></ReduxProvider></body>
    </html>
  );
}
